# note: YAML definitions for multiple components/resources can be bundled together into one YAML file
# '---' is used to separate the definitions of the components/resources

# define the `Deployment` for the mongodb server
---
# define the `Deployment` for mongo-express
---
# define the `Deployment` for flask-app
# set ImagePullPolicy to 'Never' to allow the use of the locally built image

#Version: '4.4.6-bionic'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.6-bionic
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value : root
              #valueFrom:
                #secretKeyRef:
                  #name: mongodb-secret
                  #key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              value : example
              #valueFrom:
                #secretKeyRef:
                  #name: mongodb-secret
                  #key: password  
            

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-service
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: eroot
              #valueFrom:
                #secretKeyRef:
                  #name: mongo-express-secret
                  #key: username
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: eexample
              #valueFrom:
                #secretKeyRef:
                  #name: mongo-express-secret
                  #key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: flask-app:latest
          ports:
            - containerPort: 5000
            #- nodePort: 30001
          env:
            - name: MONGO_URI
              value: mongodb://mongodb-service:27017/
          imagePullPolicy: Never
          
#mydatabase

