# define the `Secret` to define the necessary environment variables for the mongo server and mongo-express.
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: cm9vdA==
  password: cm9vdA==
  #mongousername: bW9uZ29yb290
  #mongopassword: bW9uZ29yb290
