# note: YAML definitions for multiple components/resources can be bundled together into one YAML file
# '---' is used to separate the definitions of the components/resources

# define a service for the mongodb server

---
# define a service for mongo-express
# set the type to LoadBalancer and configure the ports
# don't forget to specify a nodePort as well! a nodePort exposes the pod to applications outside the cluster. this will allow you to access the frontend admin interface from your host system

---
# define a `Service` for flask-app
# set the type to LoadBalancer and configure the ports
# don't forget to specify a nodePort as well! a nodePort exposes the pod to applications outside the cluster. this will allow you to access the frontend admin interface from your host system

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo-port
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
  
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  ports:
    - name: mongo-express-port
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
  type: LoadBalancer
  externalTrafficPolicy: Local
  #loadBalancerIP: 10.0.0.100
  
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - name: flask-port
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: LoadBalancer

  

